### ISSUE TITLE
Referencing

### ISSUE THREAD

**Issue by msdemlei** [ivoa-std/VOEvent#4]
In order to not have ugly surprises in HTML conversion, and to help when we'd like to deliver citations to ADS, I'd like it a lot if the document could be ported to use the normal ivoatex referencing (i.e., natbib, docrepo.bib for IVOA stuff, ivoabib.bib for non-IVOA common stuff, and local bibTeX for anything else.

**Comment by BaptisteCecconi** [comment]
This is done in the PR #2

**Comment by msdemlei** [comment]
Sorry, I've missed that PR for some reason.  Well, I'm closing this, trusting the stuff will eventually get merged (don't feel qualified to review that PR, though).

**Comment by BaptisteCecconi** [comment]
The current content is a first msword=>latex transcription. PR #2 is including ivoatex-friendly features.
